--- #YAML:1.0
name:               Finance-Bank-CreditMut
version:            0.12
abstract:            Check your Crédit Mutuel accounts from Perl
author:
    - Cédric Bouvier <cbouvi@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::TableExtract:  1.08
    WWW::Mechanize:      0.44
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
