# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Finance-Bank-CreditMut
version:      0.1
version_from: lib/Finance/Bank/CreditMut.pm
installdirs:  site
requires:
    Crypt::SSLeay:                 0
    HTML::TableExtract:            1.08
    WWW::Mechanize:                0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
